import type { DifferentiationBrief } from "@/types/brief";
import type { SignalsResult } from "@/types/signals";

export function briefToMarkdown(
  brief: DifferentiationBrief,
  signals: SignalsResult,
  keyword: string,
  scanId: number
): string {
  const date = new Date(brief.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [
    `# Differentiation Brief: "${keyword}"`,
    ``,
    `**Scan ID:** ${scanId}  `,
    `**Generated:** ${date}  `,
    `**Listings Analyzed:** ${signals.listingCount}  `,
    `**Price Range:** $${signals.priceBands.p25}–$${signals.priceBands.p75} (p25–p75)  `,
    ``,
    `---`,
    ``,
    `## Market Standard`,
    ``,
    brief.marketStandard.summary,
    ``,
    `**Typical formats:** ${brief.marketStandard.typicalFormats.join(", ")}  `,
    `**Typical price range:** ${brief.marketStandard.typicalPriceRange}`,
    ``,
    `---`,
    ``,
    `## Differentiators`,
    ``,
    ...brief.differentiators.map(
      (d) =>
        `**${d.id}.** ${d.claim}\n\n> *Signal:* \`${d.supportingSignal}\` — ${d.evidence}\n`
    ),
    `---`,
    ``,
    `## What's Missing`,
    ``,
    ...brief.missingFeatures.map(
      (f) => `- **${f.feature}**\n  ${f.rationale}\n  *(Signal: ${f.supportingSignal})*\n`
    ),
    `---`,
    ``,
  ];

  if (brief.buyerFrictions.length > 0) {
    lines.push(`## Buyer Frictions`, ``);
    for (const f of brief.buyerFrictions) {
      lines.push(
        `- [${f.severity.toUpperCase()}] **${f.friction}**`,
        ...(f.sourceReviews.length > 0
          ? [`  > ${f.sourceReviews.slice(0, 2).join("\n  > ")}`]
          : []),
        ``
      );
    }
    lines.push(`---`, ``);
  }

  lines.push(
    `## Winning Build Spec`,
    ``,
    `**Core problem solved:** ${brief.winningBuildSpec.coreProblemSolved}`,
    ``,
    `**Must-have features:**`,
    ...brief.winningBuildSpec.mustHaveFeatures.map((f) => `- ${f}`),
    ``,
    `**Must avoid:**`,
    ...brief.winningBuildSpec.mustAvoid.map((f) => `- ${f}`),
    ``,
    `---`,
    ``,
    `## Premium Ladder`,
    ``,
    ...brief.premiumLadder.map(
      (tier) =>
        `### ${tier.tier.charAt(0).toUpperCase() + tier.tier.slice(1)}: ${tier.label} (${tier.suggestedPriceRange})\n\n${tier.features.map((f) => `- ${f}`).join("\n")}\n`
    ),
    `---`,
    ``,
    `## Listing Angle`,
    ``,
    `**Headline:** ${brief.listingAngle.headline}`,
    ``,
    `**Subheadline:** ${brief.listingAngle.subheadline}`,
    ``,
    `**Image callouts:**`,
    ...brief.listingAngle.imageCallouts.map((c) => `- ${c}`),
    ``,
    `---`,
    ``,
    `## Risk Flags`,
    ``,
    ...brief.riskFlags.map(
      (r) =>
        `- [${r.severity.toUpperCase()}] **${r.flag}**\n  *Mitigation:* ${r.mitigation}\n`
    ),
    `---`,
    ``,
    `*Generated by Etsy Engine Module 1 — Structural Edge Analyzer*`,
  );

  return lines.join("\n");
}
